[package]
name = "contract-abi"
version = "0.0.1"
authors = [ "coldiary",]
edition = "2021"
publish = false

[dev-dependencies]

[dependencies.contract]
path = ".."

[dependencies.elrond-wasm]
version = "0.21.1"

[dependencies.elrond-wasm-debug]
version = "0.21.1"
