urls:
  api: 'https://devnet-api.elrond.com'
  ipfs: 'https://ipfs.io/ipfs'
  swagger:
    - 'http://localhost:3001'
  redis: '127.0.0.1'
features:
  publicApi: true
  privateApi: true
  transactionProcessor: true
security:
  jwtSecret: ''
contracts:
  tips: 'erd1qqqqqqqqqqqqqpgqremaaqc6z25j4tv8w0u4ke9qqqrw6r3du4aqkygha9'
  trade: 'erd1qqqqqqqqqqqqqpgqsa0t6waa9rlzrmny6hnn30kg7m22daddu4aqjfagyx'
