urls:
  api: 'https://api.elrond.com'
  ipfs: 'https://ipfs.io/ipfs'
  swagger:
    - 'https://api.fellowship.tools'
  redis: 'redis'
features:
  publicApi: true
  privateApi: true
  transactionProcessor: false
security:
  jwtSecret: ''
contracts:
  tips: ''
  trade: ''
